
title: "zena znaci revolucija"
email: your-email@example.com
description: >-
  A blog devoted to writings on all things feminist
baseurl: ""
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Header pages
header_pages:
  - about.md
  - articles.md
  - resources.md
  - contact.md
